// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OOAppDevToolBox
{
    internal sealed partial class Vsix
    {
        public const string Id = "OOAppDevToolBox.a4e460d5-76d4-4cb4-be99-5ea16cd863ac";
        public const string Name = "OOAppDevToolBox";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jim Liakos";
        public const string Tags = "";
    }
}
