//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAdvantech.Authentication.Proxies
{
    using System;
    
    
    public sealed class CNSPr_IAuth_AuthStateChange : OOAdvantech.Remoting.EventConsumerHandler
    {
        
        public void Invoke(object sender, OOAdvantech.Authentication.AuthStateEventArgs authArgs)
        {
            object[] args = new object[2];
            System.Type[] argsTypes = new System.Type[2];
            args[0] = sender;
            argsTypes[0] = typeof(object);
            args[1] = authArgs;
            argsTypes[1] = typeof(OOAdvantech.Authentication.AuthStateEventArgs);
            object retValue = this.Invoke(typeof(OOAdvantech.Authentication.AuthStateChangeHandler), "Invoke", args, argsTypes);
        }
        
        public override void AddEventHandler(object target, System.Reflection.EventInfo eventInfo)
        {
            eventInfo.AddEventHandler(target, new OOAdvantech.Authentication.AuthStateChangeHandler(this.Invoke));
        }
        
        public override void RemoveEventHandler(object target, System.Reflection.EventInfo eventInfo)
        {
            eventInfo.RemoveEventHandler(target, new OOAdvantech.Authentication.AuthStateChangeHandler(this.Invoke));
        }
    }
    
    public sealed class CNSPr_IAuth_IdTokenChange : OOAdvantech.Remoting.EventConsumerHandler
    {
        
        public void Invoke(object sender, OOAdvantech.Authentication.IdTokenEventArgs idTokenArgs)
        {
            object[] args = new object[2];
            System.Type[] argsTypes = new System.Type[2];
            args[0] = sender;
            argsTypes[0] = typeof(object);
            args[1] = idTokenArgs;
            argsTypes[1] = typeof(OOAdvantech.Authentication.IdTokenEventArgs);
            object retValue = this.Invoke(typeof(OOAdvantech.Authentication.IdTokenChangeHandler), "Invoke", args, argsTypes);
        }
        
        public override void AddEventHandler(object target, System.Reflection.EventInfo eventInfo)
        {
            eventInfo.AddEventHandler(target, new OOAdvantech.Authentication.IdTokenChangeHandler(this.Invoke));
        }
        
        public override void RemoveEventHandler(object target, System.Reflection.EventInfo eventInfo)
        {
            eventInfo.RemoveEventHandler(target, new OOAdvantech.Authentication.IdTokenChangeHandler(this.Invoke));
        }
    }
}
